#!/bin/sh
exec tmux \
  splitw -h \;\
  send asciiquarium ENTER \;\
  selectp -t 1 \;\
  splitw \;\
  send bashmatrix ENTER \;\
  selectp -t 1 \;\
  send watchcow ENTER \;\
  resizep -t 2 -y 5 -x 44

