#!/bin/bash

# script to set a random background image on gnome desktop

export WP_IMAGE_PATH=/mnt/data/Documents/wallpaper/Bing

shopt -s nullglob

wallpapers=(
  $WP_IMAGE_PATH/*.jpg
  $WP_IMAGE_PATH/*.jpeg
  $WP_IMAGE_PATH/*.png
)

wallpapers_size=${#wallpapers[*]}

# set in order
#while [ $index -lt $wallpapers_size ]
#do
#  gsettings set org.gnome.desktop.background picture-uri ${wallpapers[$index]}
#  if [ $(($index+1)) -eq $wallpapers_size ]
#  then
#    index=0
#  else
#    index=$(($index+1))
#  fi
#  sleep 15m
#done

# set random
while true
do
  random_index=$(($RANDOM % $wallpapers_size))
  gsettings set org.gnome.desktop.background picture-uri ${wallpapers[$random_index]}
  gsettings set org.gnome.desktop.background picture-uri-dark ${wallpapers[$random_index]}
  sleep 15m
done

