#+title: Emacs From Scratch Configuration
#+PROPERTY: header-args:emacs-lisp :tangle ~/.emacs.d/init.el :mkdirp yes

* Welcome!

This configuration started based on the *Emacs From Scratch* series, but has evolved over time.
This file generates [[file:init.el][init.el]] which can be loaded by Emacs at startup.

Links to repos or sites I have acquire some setup examples:
- https://systemcrafters.cc/
- https://github.com/jakebox/jake-emacs

The following is some initial font setup.
#+begin_src emacs-lisp

  ;; NOTE: init.el is now generated from Emacs.org.  Please edit that file
  ;;       in Emacs and init.el will be generated automatically!

  ;; You will most likely need to adjust this font size for your system!
  (defvar efs/default-font-size 160)
  (defvar efs/default-variable-font-size 160)

  ;; Make frame transparency overridable
  (defvar efs/frame-transparency '(100 . 100))

#+end_src

** Prerequsites
There are a number of packages that have dependencies on other applications that should be installed on the host system.
I will try to capture them here and hope to keep them in sync with changes to this configuration.
- fonts - see [[Font Configuration]]
- ripgrep (rg) - faster grep
- fzf - fuzzy file search
- latex - installation varies depending on distribution.
  - Fedora:
    - sudo dnf install texlive-scheme-medium

The first time you load your configuration on a new machine, you'll need to run `M-x all-the-icons-install-fonts` so that mode line icons display correctly.  See [[Better Modeline]].

* Tips for Use

In this document there are links that lead you to documentation for the various packages used.  If you're looking at this file in Emacs, you can put your cursor on a link and press =C-c C-o= or run =M-x org-open-at-point= to open the link in your web browser.

** OS specific code
Use the system-type variable to determine on which OS Emacs is running.
There is another variable window-system which also contains the OS type but it will not be populated when Emacs is running in server mode.
Only use system-type so that you can run emacs in server or client mode.

#+begin_src emacs-lisp :tangle no
(pcase system-type
  ('gnu/linux "It's Linux")
  ('windows-nt "It's Windows")
  ('darwin "It's OS X"))
#+end_src

* System specific setup
#+begin_src emacs-lisp
    (let ((env-var-value (getenv "MSYSTEM_PREFIX")))
      (if (not (string-empty-p env-var-value))
	  (progn
	    (setq package-gnupghome-dir "/home/jeff/.emacs.d/elpa/gnupg")
	    (setq msystem t))
	(setq msystem f)))
#+end_src
* Package System Setup

Emacs has a built in package manager but it doesn't make it easy to automatically install packages on a new system the first time you pull down your configuration.  [[https://github.com/jwiegley/use-package][use-package]] is a really helpful package used in this configuration to make it a lot easier to automate the installation and configuration.

#+begin_src emacs-lisp

  ;; Initialize package sources
  (require 'package)

  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
                           ("org" . "https://orgmode.org/elpa/")
                           ("elpa" . "https://elpa.gnu.org/packages/")))

  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))

    ;; Initialize use-package on non-Linux platforms
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (require 'use-package)
  (setq use-package-always-ensure t)

#+end_src

* Custom Files

Load custom emacs lisp files here.
#+begin_src emacs-lisp
  (setq jem/custom-emacs "~/.emacs.d/custom-emacs")
  ;; load private file defining some variables
  (load (expand-file-name "private.el" user-emacs-directory))
  (add-to-list 'load-path (directory-file-name (concat jem/custom-emacs "/lisp")))
  (setq bookmark-default-file (concat jem/custom-emacs "/bookmarks"))
  (setq custom-theme-directory (expand-file-name "themes" jem/custom-emacs))
#+end_src

* Basic Configuration

This section contains genral configuration of emacs settings.  UI related changes are made in sections below.

#+begin_src emacs-lisp
    ;; set tab width
    (setq tab-width 4)
    (setq standard-indent 4)

    ;; When emacs asks for 'yes' or 'no', ask 'y' or 'n' instead.
    (fset 'yes-or-no-p 'y-or-n-p)

    ;; Confirm to quit
    (setq confirm-kill-emacs 'yes-or-no-p)

    ;; Don't resize the frames in steps; it looks weird, especially in tiling window
    ;; managers, where it can leave unseemly gaps.
    (setq frame-resize-pixelwise t)

    (setq
     ;; If the frame contains multiple windows, scroll the one under the cursor
     ;; instead of the one that currently has keyboard focus.
     mouse-wheel-follow-mouse 't
     ;; Completely disable mouse wheel acceleration to avoid speeding away.
     mouse-wheel-progressive-speed nil
     ;; The most important setting of all! Make each scroll-event move 2 lines at
     ;; a time (instead of 5 at default). Simply hold down shift to move twice as
     ;; fast, or hold down control to move 3x as fast. Perfect for trackpads.
     mouse-wheel-scroll-amount '(2 ((shift) . 4) ((control) . 6)))

    ;; Uses system trash rather than deleting forever
    (setq trash-directory (concat jeff/home "/.local/share/Trash/files"))
    (setq delete-by-moving-to-trash t)

    ;; BACKUPS/LOCKFILES --------
    ;; Don't generate backups or lockfiles by adding the following 2 lines.
    ;;    make-backup-files nil
    ;;    create-lockfiles nil
    ;; But in case the user does enable it, some sensible defaults:
    (setq
          version-control t     ; number each backup file
          backup-by-copying t   ; instead of renaming current file (clobbers links)
          delete-old-versions t ; clean up after itself
          kept-old-versions 2
          kept-new-versions 2
          backup-directory-alist (list (cons "." (concat user-emacs-directory "backup/"))))

  (use-package recentf
    :ensure nil
    :config
    (setq   recentf-auto-cleanup 'never
            recentf-max-menu-items 0
            recentf-max-saved-items 200))

  (require 'uniquify)
  (setq uniquify-buffer-name-style 'forward)

  ;; ENCODING -------------
  (when (fboundp 'set-charset-priority)
    (set-charset-priority 'unicode))       ; pretty
  (prefer-coding-system 'utf-8)            ; pretty
  (setq locale-coding-system 'utf-8)       ; please

  (setq browse-url-firefox-program "/usr/bin/firefox")
  (setq browse-url-brave-program "/usr/bin/brave")

  (setq blink-cursor-interval 0.6)

  ;; MISC OPTIMIZATIONS ----
  ;; Emacs "updates" its ui more often than it needs to, so we slow it down
  ;; slightly from 0.5s:
  ;;; optimizations (froom Doom's core.el). See that file for descriptions.
  (setq idle-update-delay 1.0)

  ;; Disabling bidi (bidirectional editing stuff)
  ;; Disables bi-directional editing (like if I wrote in both Hebrew and English)
  (setq-default bidi-display-reordering 'left-to-right
                bidi-paragraph-direction 'left-to-right)
  (setq bidi-inhibit-bpa t)  ; emacs 27 only - disables bidirectional parenthesis

  (setq-default cursor-in-non-selected-windows nil)
  (setq highlight-nonselected-windows nil)
  (setq fast-but-imprecise-scrolling t)
  (setq inhibit-compacting-font-caches t)

  (setq save-interprogram-paste-before-kill t
        apropos-do-all t
        mouse-yank-at-point t)
  ;; treat underscore as part of word
  (defun underscore-part-of-word-hook ()
    (modify-syntax-entry ?_ "w"))
  ;; linum makes viewing images slower
  (add-hook 'image-mode-hook (lambda () (linum-mode -1))) ;; linum doesnt work well with image-mode
  #+end_src
* Basic UI Configuration

This section configures basic UI settings that remove unneeded elements to make Emacs look a lot more minimal and modern.
The menu bar can sometimes be helpful and can be turned back on with =(menu-bar-mode 1)=.

#+begin_src emacs-lisp

  (setq inhibit-startup-message t)

  (scroll-bar-mode -1)        ; Disable visible scrollbar
  (tool-bar-mode -1)          ; Disable the toolbar
  (tooltip-mode -1)           ; Disable tooltips
  (set-fringe-mode 10)        ; Give some breathing room

  (menu-bar-mode -1)            ; Disable the menu bar

  ;; Set up the visible bell
  (setq visible-bell t)

  (column-number-mode)
  (global-display-line-numbers-mode t)

  ;; Set frame transparency
  (set-frame-parameter (selected-frame) 'alpha efs/frame-transparency)
  (add-to-list 'default-frame-alist `(alpha . ,efs/frame-transparency))
  ;; (set-frame-parameter (selected-frame) 'fullscreen 'maximized)
  ;; (add-to-list 'default-frame-alist '(fullscreen . maximized))

  ;; Disable line numbers for some modes
  (dolist (mode '(org-mode-hook
                  term-mode-hook
                  shell-mode-hook
                  treemacs-mode-hook
                  eshell-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))

#+end_src

** Font Configuration

I am using the **GoMono Nerd Font** fonts for this configuration.
These will need to be downloaded and installed if not already installed or change the setting here to another installed font.

#+begin_src emacs-lisp
  (defun efs/set-font-faces ()
      (message "Setting faces!")
      (set-face-attribute 'default nil :font "ShureTechMono Nerd Font" :height efs/default-font-size)

      ;; Set the fixed pitch face
      (set-face-attribute 'fixed-pitch nil :font "ShureTechMono Nerd Font" :height efs/default-font-size)

      ;; Set the variable pitch face
      (set-face-attribute 'variable-pitch nil :font "ShureTechMono Nerd Font" :height efs/default-variable-font-size :weight 'regular))

  ;; If running as daemon need to reset fonts/modeline after creating new frame
  (if (daemonp)
      (add-hook 'after-make-frame-functions
                (lambda (frame)
                  (setq doom-modeline-icon t)
                  (with-selected-frame frame
                    (efs/set-font-faces))))
      (efs/set-font-faces))

  (use-package unicode-fonts
  :ensure t
  :config
    (unicode-fonts-setup))
#+end_src

* Keybinding Configuration

This configuration uses [[https://evil.readthedocs.io/en/latest/index.html][evil-mode]] for a Vi-like modal editing experience.  [[https://github.com/noctuid/general.el][general.el]] is used for easy keybinding configuration that integrates well with which-key.  [[https://github.com/emacs-evil/evil-collection][evil-collection]] is used to automatically configure various Emacs modes with Vi-like keybindings for evil-mode.

#+begin_src emacs-lisp

  ;; Make these org-mode key bindings global
  (global-set-key (kbd "C-c l") #'org-store-link)
  (global-set-key (kbd "C-c C-l") #'org-store-link)
  (global-set-key (kbd "C-c a") #'org-agenda)
  (global-set-key (kbd "C-c c") #'org-capture)

  ;; Make ESC quit prompts
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)

  (use-package general
    :config
    (general-create-definer rune/leader-keys
      :keymaps '(normal insert visual emacs)
      :prefix "SPC"
      :global-prefix "C-SPC")

    (rune/leader-keys
      "TAB" 'previous-buffer
      "SPC" (general-simulate-key "C-x")
      "c"   (general-simulate-key "C-c")
      "h"   (general-simulate-key "C-h")
      "u"   (general-simulate-key "C-u")
      "x"   (general-simulate-key "C-x")
      ;; "Applications"
      "a" '(nil :which-key "applications")
      "ao" '(org-agenda :which-key "org-agenda")
      "aC" '(calc :which-key "calc")
      "ac" '(org-capture :which-key "org-capture")
      "aqq" '(org-ql-view :which-key "org-ql-view")
      "aqs" '(org-ql-search :which-key "org-ql-search")
      "ab" '(nil :which-key "browse url")
      "abf" '(browse-url-firefox :which-key "firefox")
      "abc" '(browse-url-brave :which-key "brave")
      ;; Buffer operations
      "b"   '(:ignore t :which-key "buffer")
      "bb"  'mode-line-other-buffer
      "bd"  'kill-this-buffer
      "b]"  'next-buffer
      "b["  'previous-buffer
      "bq"  'kill-buffer-and-window
      "bR"  'rename-file-and-buffer
      "br"  'revert-buffer
      ;; File operations
      "f"  '(:ignore t :which-key "files")
      "fc"  'write-file
      "fe"  '(:ignore t :which-key "emacs")
      "fed" 'find-user-init-file
      "feR" 'load-user-init-file
      "ff"  'find-file
      "fl"  'find-file-literally
      "fR"  'rename-file-and-buffer
      "fs"  'save-buffer
      ;; Jeff
      "j" '(nil :which-key "jeff")
      "ja" '((lambda() (interactive)(find-file (concat jeff/dotfiles "shell.d/aliases.sh"))) :which-key "aliases")
      "jb" '((lambda() (interactive)(find-file (concat jeff/kb "MOC.org"))) :which-key "KB-MOC.org")
      "jd" '((lambda() (interactive)(find-file jeff/dotfiles)) :which-key "dotfiles")
      "je" '((lambda() (interactive)(find-file (concat jeff/dotfiles "emacs.d/Emacs.org"))) :which-key "Emacs.org")
      "ji" '((lambda() (interactive)(find-file (concat jeff/dotfiles "i3/config"))) :which-key "i3-config")
      "jk" '((lambda() (interactive)(find-file jeff/kb)) :which-key "Notes")
      "jm" '((lambda() (interactive)(find-file (concat jeff/md "MOC.md"))) :which-key "MOC.md")
      "jp" '((lambda() (interactive)(find-file (concat jeff/kb "projects/projects.org"))) :which-key "projects.org")
      ;;"jk" '(nil :which-key "agenda/ql")
      ;;"jkq" '((lambda () (interactive) (org-ql-view "Jeff QL Todo")) :which-key ;;"jeff ql")
      ;; Projectile
      "p"  '(:ignore t :which-key "Projectile")
      "ph" 'projectile-find-other-file
      "pH" 'projectile-find-other-file-other-window
      "ps" 'projectile-grep
      "pf" 'projectile--find-file
      "pF" 'projectile-find-file-other-window
      "pt" 'projectile-run-shell
      ;; Toggles
      "t"  '(:ignore t :which-key "toggles")
      "tt" '(counsel-load-theme :which-key "choose theme")
      ;; Window operations
      "w"   '(:ignore t :which-key "window")
      "wm"  'maximize-window
      "w/"  'split-window-horizontally
      "wv"  'split-window-vertically
      "wm"  'maximize-window
      "ww"  'other-window
      "wd"  'delete-window
      "wD"  'delete-other-windows))

  (use-package evil
    :init
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    (setq evil-want-C-u-scroll t)
    (setq evil-want-C-i-jump nil)
    :config
    (evil-mode 1)
    (define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)
    (define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join)

    ;; Use visual line motions even outside of visual-line-mode buffers
    (evil-global-set-key 'motion "j" 'evil-next-visual-line)
    (evil-global-set-key 'motion "k" 'evil-previous-visual-line)

    (evil-set-initial-state 'messages-buffer-mode 'normal)
    (evil-set-initial-state 'dashboard-mode 'normal))

  (use-package evil-collection
    :after evil
    :config
    (evil-collection-init))

  (use-package key-chord
    :init
    (setq key-chord-two-keys-delay 0.5)
    (key-chord-mode 1)
    (key-chord-define evil-insert-state-map "jj" 'evil-normal-state))
#+end_src

* Emacs-Lisp Mode ~,~ Bindings

Sets up comma leader key for elisp mode.
#+begin_src emacs-lisp
(general-def
  :prefix ","
  :states 'motion
  :keymaps 'emacs-lisp-mode-map
  "" nil
  "e" '(nil :which-key "eval")
  "es" '(eval-last-sexp :which-key "eval-sexp")
  "er" '(eval-region :which-key "eval-region")
  "eb" '(eval-buffer :which-key "eval-buffer")

  "c" '(check-parens :which-key "check parens")
  "I" '(indent-region :which-key "indent-region")
  )
#+end_src

* Enhanced eww
#+begin_src emacs-lisp
;;; enhanced eww
  (use-package shrface
    :ensure t
    :defer t
    :config
    (shrface-basic)
    (shrface-trial)
    (shrface-default-keybindings) ; setup default keybindings
    (setq shrface-href-versatile t)
    (define-key eww-mode-map (kbd "<tab>") 'shrface-outline-cycle)
    (define-key eww-mode-map (kbd "<backtab>") 'shrface-outline-cycle-buffer))

  (use-package eww
    :defer t
    :bind ("C-x w w" . eww)
    :init
    (add-hook 'eww-after-render-hook #'shrface-mode)
    :config
    (require 'shrface))
#+end_src
* Org Mode ~,~ Bindings

Org mode comma leader key bindings.
#+begin_src emacs-lisp
(general-define-key
  :prefix ","
  :states 'motion
  :keymaps '(org-mode-map) ;; Available in org mode, org agenda
  "" nil
  "A" '(org-archive-subtree-default :which-key "org-archive")
  "a" '(org-agenda :which-key "org agenda")
  "6" '(org-sort :which-key "sort")
  "c" '(org-capture :which-key "org-capture")
  "s" '(org-schedule :which-key "schedule")
  "d" '(org-deadline :which-key "deadline")
  "g" '(counsel-org-goto :which-key "goto heading")
  "t" '(counsel-org-tag :which-key "set tags")
  "p" '(org-set-property :which-key "set property")
  "e" '(org-export-dispatch :which-key "export org")
  "B" '(org-toggle-narrow-to-subtree :which-key "toggle narrow to subtree")
  "H" '(org-html-convert-region-to-html :which-key "convert region to html")

  ;; org-babel
  "b" '(nil :which-key "babel")
  "bt" '(org-babel-tangle :which-key "org-babel-tangle")
  "bb" '(org-edit-special :which-key "org-edit-special")
  "bc" '(org-edit-src-abort :which-key "org-edit-src-abort")

  ;; insert
  "i" '(nil :which-key "insert")

  "it" '(nil :which-key "tables")
  "itt" '(org-table-create :which-key "create table")
  "itl" '(org-table-insert-hline :which-key "table hline")

  "il" '(org-insert-link :which-key "link")

  ;; clocking
  "c" '(nil :which-key "clocking")
  "ci" '(org-clock-in :which-key "clock in")
  "co" '(org-clock-out :which-key "clock out")
  "cj" '(org-clock-goto :which-key "jump to clock")
)


(general-define-key
  :prefix ","
  :states 'motion
  :keymaps '(org-agenda-mode-map) ;; Available in org mode, org agenda
  "" nil
  "a" '(org-agenda :which-key "org agenda")
  "c" '(org-capture :which-key "org-capture")
  "s" '(org-agenda-schedule :which-key "schedule")
  "d" '(org-agenda-deadline :which-key "deadline")
  "t" '(org-agenda-set-tags :which-key "set tags")
  ;; clocking
  "c" '(nil :which-key "clocking")
  "ci" '(org-agenda-clock-in :which-key "clock in")
  "co" '(org-agenda-clock-out :which-key "clock out")
  "cj" '(org-clock-goto :which-key "jump to clock")
)
#+end_src

* UI Configuration

** Command Log Mode

[[https://github.com/lewang/command-log-mode][command-log-mode]] is useful for displaying a panel showing each key binding you use in a panel on the right side of the frame.  Great for live streams and screencasts!

#+begin_src emacs-lisp

(use-package command-log-mode)

#+end_src

** Color Theme

[[https://github.com/hlissner/emacs-doom-themes][doom-themes]] is a great set of themes with a lot of variety and support for many different Emacs modes.  Taking a look at the [[https://github.com/hlissner/emacs-doom-themes/tree/screenshots][screenshots]] might help you decide which one you like best.  You can also run =M-x counsel-load-theme= to choose between them easily.

#+begin_src emacs-lisp

  (use-package doom-themes)
  ;;  :init (load-theme 'doom-dracula t))
  ;;(use-package doom-themes
  ;;  :init (load-theme 'doom-tomorrow-night t))
  (use-package gruvbox-theme)
  ;;  :init (progn (load-theme 'gruvbox-dark-hard t)
  ;;               (load-theme 'gruvbox-light-medium t)
  ;;               (enable-theme 'gruvbox-dark-hard))
  ;;  :defer t
  ;;  :ensure t)

  (use-package ef-themes
    :ensure t
    ;; :init (load-theme 'ef-elea-light))
    :init (load-theme 'ef-dream))
#+end_src

** Better Modeline

[[https://github.com/seagle0128/doom-modeline][doom-modeline]] is a very attractive and rich (yet still minimal) mode line configuration for Emacs.  The default configuration is quite good but you can check out the [[https://github.com/seagle0128/doom-modeline#customize][configuration options]] for more things you can enable or disable.

*NOTE:* The first time you load your configuration on a new machine, you'll need to run `M-x all-the-icons-install-fonts` so that mode line icons display correctly.

#+begin_src emacs-lisp

(use-package all-the-icons)

(use-package doom-modeline
  :init (doom-modeline-mode 1)
  :custom ((doom-modeline-height 15)))

#+end_src

** Which Key

[[https://github.com/justbur/emacs-which-key][which-key]] is a useful UI panel that appears when you start pressing any key binding in Emacs to offer you all possible completions for the prefix.  For example, if you press =C-c= (hold control and press the letter =c=), a panel will appear at the bottom of the frame displaying all of the bindings under that prefix and which command they run.  This is very useful for learning the possible key bindings in the mode of your current buffer.

#+begin_src emacs-lisp

(use-package which-key
  :init (which-key-mode)
  :diminish which-key-mode
  :config
  (setq which-key-idle-delay 1))

#+end_src

** Ivy and Counsel

[[https://oremacs.com/swiper/][Ivy]] is an excellent completion framework for Emacs.  It provides a minimal yet powerful selection menu that appears when you open files, switch buffers, and for many other tasks in Emacs.  Counsel is a customized set of commands to replace `find-file` with `counsel-find-file`, etc which provide useful commands for each of the default completion commands.

[[https://github.com/Yevgnen/ivy-rich][ivy-rich]] adds extra columns to a few of the Counsel commands to provide more information about each item.

#+begin_src emacs-lisp

  (use-package ivy
    :diminish
    :bind (("C-s" . swiper)
           :map ivy-minibuffer-map
           ("TAB" . ivy-alt-done)
           ("C-l" . ivy-alt-done)
           ("C-j" . ivy-next-line)
           ("C-k" . ivy-previous-line)
           :map ivy-switch-buffer-map
           ("C-k" . ivy-previous-line)
           ("C-l" . ivy-done)
           ("C-d" . ivy-switch-buffer-kill)
           :map ivy-reverse-i-search-map
           ("C-k" . ivy-previous-line)
           ("C-d" . ivy-reverse-i-search-kill))
    :config
    (ivy-mode 1))

  (use-package ivy-rich
    :init
    (ivy-rich-mode 1))

  (use-package counsel
    :bind (("C-M-j" . 'counsel-switch-buffer)
           :map minibuffer-local-map
           ("C-r" . 'counsel-minibuffer-history))
    :custom
    (counsel-linux-app-format-function #'counsel-linux-app-format-function-name-only)
    :config
    (counsel-mode 1))

#+end_src

** Helpful Help Commands

[[https://github.com/Wilfred/helpful][Helpful]] adds a lot of very helpful (get it?) information to Emacs' =describe-= command buffers.  For example, if you use =describe-function=, you will not only get the documentation about the function, you will also see the source code of the function and where it gets used in other places in the Emacs configuration.  It is very useful for figuring out how things work in Emacs.

#+begin_src emacs-lisp

  (use-package helpful
    :custom
    (counsel-describe-function-function #'helpful-callable)
    (counsel-describe-variable-function #'helpful-variable)
    :bind
    ([remap describe-function] . counsel-describe-function)
    ([remap describe-command] . helpful-command)
    ([remap describe-variable] . counsel-describe-variable)
    ([remap describe-key] . helpful-key))

#+end_src

** Text Scaling

This is an example of using [[https://github.com/abo-abo/hydra][Hydra]] to design a transient key binding for quickly adjusting the scale of the text on screen.  We define a hydra that is bound to =leader t s= and, once activated, =j= and =k= increase and decrease the text scale.  You can press any other key (or =f= specifically) to exit the transient key map.

#+begin_src emacs-lisp

  (use-package hydra)

  (defhydra hydra-text-scale (:timeout 4)
    "scale text"
    ("j" text-scale-increase "in")
    ("k" text-scale-decrease "out")
    ("f" nil "finished" :exit t))

  (rune/leader-keys
    "ts" '(hydra-text-scale/body :which-key "scale text"))

#+end_src

* Org Mode

[[https://orgmode.org/][Org Mode]] is one of the hallmark features of Emacs.  It is a rich document editor, project planner, task and time tracker, blogging engine, and literate coding utility all wrapped up in one package.

** Better Font Faces

The =efs/org-font-setup= function configures various text faces to tweak the sizes of headings and use variable width fonts in most cases so that it looks more like we're editing a document in =org-mode=.  We switch back to fixed width (monospace) fonts for code blocks and tables so that they display correctly.

#+begin_src emacs-lisp

  (defun efs/org-font-setup ()
    ;; Replace list hyphen with dot
    (font-lock-add-keywords 'org-mode
                            '(("^ *\\([-]\\) "
                               (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))

    ;; Set faces for heading levels
    (dolist (face '((org-level-1 . 1.2)
                    (org-level-2 . 1.1)
                    (org-level-3 . 1.05)
                    (org-level-4 . 1.0)
                    (org-level-5 . 1.1)
                    (org-level-6 . 1.1)
                    (org-level-7 . 1.1)
                    (org-level-8 . 1.1)))
      (set-face-attribute (car face) nil :font "GoMono Nerd Font" :weight 'regular :height (cdr face)))

    ;; Ensure that anything that should be fixed-pitch in Org files appears that way
    (set-face-attribute 'org-block nil :foreground nil :inherit 'fixed-pitch)
    (set-face-attribute 'org-code nil   :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-table nil   :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-meta-line nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-checkbox nil :inherit 'fixed-pitch))

#+end_src

** Basic Config

This section contains the basic configuration for =org-mode= plus the configuration for Org agendas and capture templates.  There's a lot to unpack in here so I'd recommend watching the videos for [[https://youtu.be/VcgjTEa0kU4][Part 5]] and [[https://youtu.be/PNE-mgkZ6HM][Part 6]] for a full explanation.

#+begin_src emacs-lisp

    (defun efs/org-mode-setup ()
      (org-indent-mode)
      (variable-pitch-mode 1)
      (visual-line-mode 1))

    (use-package org
      :pin org
      :hook (org-mode . efs/org-mode-setup)
      :config
      (setq org-ellipsis " ▾")

      (setq org-agenda-start-with-log-mode t)
      (setq org-log-done 'time)
      (setq org-log-into-drawer t)
      (setq org-M-RET-may-split-line '((default . nil)))
      (setq org-insert-heading-respect-content t)

  ;;    (setq org-agenda-files
  ;;          '("~/Projects/Code/emacs-from-scratch/OrgFiles/Tasks.org"
  ;;            "~/Projects/Code/emacs-from-scratch/OrgFiles/Habits.org"
  ;;            "~/Projects/Code/emacs-from-scratch/OrgFiles/Birthdays.org"))
      ;;(setq org-agenda-files '("" jeff/kb))

      (require 'org-habit)
      (add-to-list 'org-modules 'org-habit)
      (setq org-habit-graph-column 60)

      (setq org-todo-keywords
        '((sequence "TODO(t)" "NEXT(n)" "|" "DONE(d!)")
          (sequence "BACKLOG(b)" "PLAN(p)" "READY(r)" "ACTIVE(a)" "REVIEW(v)" "WAIT(w@/!)" "HOLD(h)" "|" "COMPLETED(c)" "CANC(k@)")))

      (setq org-refile-targets
        '(("Archive.org" :maxlevel . 1)
          ("Tasks.org" :maxlevel . 1)))

      ;; Save Org buffers after refiling!
      (advice-add 'org-refile :after 'org-save-all-org-buffers)

      (setq org-tag-alist
        '((:startgroup)
           ; Put mutually exclusive tags here
           (:endgroup)
           ("@errand" . ?E)
           ("@home" . ?H)
           ("@work" . ?W)
           ("agenda" . ?a)
           ("planning" . ?p)
           ("publish" . ?P)
           ("batch" . ?b)
           ("note" . ?n)
           ("idea" . ?i)))

      ;; Configure custom agenda views
      (setq org-agenda-custom-commands
       '(("d" "Dashboard"
         ((agenda "" ((org-deadline-warning-days 7)))
          (todo "NEXT"
            ((org-agenda-overriding-header "Next Tasks")))
          (tags-todo "agenda/ACTIVE" ((org-agenda-overriding-header "Active Projects")))))

        ("n" "Next Tasks"
         ((todo "NEXT"
            ((org-agenda-overriding-header "Next Tasks")))))

        ("W" "Work Tasks" tags-todo "+work-email")

        ;; Low-effort next actions
        ("e" tags-todo "+TODO=\"NEXT\"+Effort<15&+Effort>0"
         ((org-agenda-overriding-header "Low Effort Tasks")
          (org-agenda-max-todos 20)
          (org-agenda-files org-agenda-files)))

        ("w" "Workflow Status"
         ((todo "WAIT"
                ((org-agenda-overriding-header "Waiting on External")
                 (org-agenda-files org-agenda-files)))
          (todo "REVIEW"
                ((org-agenda-overriding-header "In Review")
                 (org-agenda-files org-agenda-files)))
          (todo "PLAN"
                ((org-agenda-overriding-header "In Planning")
                 (org-agenda-todo-list-sublevels nil)
                 (org-agenda-files org-agenda-files)))
          (todo "BACKLOG"
                ((org-agenda-overriding-header "Project Backlog")
                 (org-agenda-todo-list-sublevels nil)
                 (org-agenda-files org-agenda-files)))
          (todo "READY"
                ((org-agenda-overriding-header "Ready for Work")
                 (org-agenda-files org-agenda-files)))
          (todo "ACTIVE"
                ((org-agenda-overriding-header "Active Projects")
                 (org-agenda-files org-agenda-files)))
          (todo "COMPLETED"
                ((org-agenda-overriding-header "Completed Projects")
                 (org-agenda-files org-agenda-files)))
          (todo "CANC"
                ((org-agenda-overriding-header "Cancelled Projects")
                 (org-agenda-files org-agenda-files)))))))

      (setq org-capture-templates
        `(("t" "Tasks / Projects")
          ("tt" "Task" entry (file+olp "~/Projects/Code/emacs-from-scratch/OrgFiles/Tasks.org" "Inbox")
               "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1)

          ("j" "Journal Entries")
          ("jj" "Journal" entry
               (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
               "\n* %<%I:%M %p> - Journal :journal:\n\n%?\n\n"
               ;; ,(dw/read-file-as-string "~/Notes/Templates/Daily.org")
               :clock-in :clock-resume
               :empty-lines 1)
          ("jm" "Meeting" entry
               (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
               "* %<%I:%M %p> - %a :meetings:\n\n%?\n\n"
               :clock-in :clock-resume
               :empty-lines 1)

          ("w" "Workflows")
          ("we" "Checking Email" entry (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
               "* Checking Email :email:\n\n%?" :clock-in :clock-resume :empty-lines 1)

          ("m" "Metrics Capture")
          ("mw" "Weight" table-line (file+headline "~/Projects/Code/emacs-from-scratch/OrgFiles/Metrics.org" "Weight")
           "| %U | %^{Weight} | %^{Notes} |" :kill-buffer t)))

      (define-key global-map (kbd "C-c j")
        (lambda () (interactive) (org-capture nil "jj")))

      (efs/org-font-setup))

#+end_src

*** Nicer Heading Bullets

[[https://github.com/sabof/org-bullets][org-bullets]] replaces the heading stars in =org-mode= buffers with nicer looking characters that you can control.  Another option for this is [[https://github.com/integral-dw/org-superstar-mode][org-superstar-mode]] which we may cover in a later video.

#+begin_src emacs-lisp

  (use-package org-bullets
    :after org
    :hook (org-mode . org-bullets-mode)
    :custom
    (org-bullets-bullet-list '("◉" "○" "●" "○" "●" "○" "●")))

#+end_src

*** Center Org Buffers

We use [[https://github.com/joostkremers/visual-fill-column][visual-fill-column]] to center =org-mode= buffers for a more pleasing writing experience as it centers the contents of the buffer horizontally to seem more like you are editing a document.  This is really a matter of personal preference so you can remove the block below if you don't like the behavior.

#+begin_src emacs-lisp

  (defun efs/org-mode-visual-fill ()
    (setq visual-fill-column-width 100
          visual-fill-column-center-text t)
    (visual-fill-column-mode 1))

  (use-package visual-fill-column
    :hook (org-mode . efs/org-mode-visual-fill))

#+end_src

** Configure Babel Languages

To execute or export code in =org-mode= code blocks, you'll need to set up =org-babel-load-languages= for each language you'd like to use.  [[https://orgmode.org/worg/org-contrib/babel/languages.html][This page]] documents all of the languages that you can use with =org-babel=.

#+begin_src emacs-lisp

  (org-babel-do-load-languages
    'org-babel-load-languages
    '((emacs-lisp . t)
      (awk . t)
      (C . t)
      (shell . t)
      (python . t)))

  (push '("conf-unix" . conf-unix) org-src-lang-modes)
  (setq org-src-preserve-indentation t)

#+end_src

** Structure Templates

Org Mode's [[https://orgmode.org/manual/Structure-Templates.html][structure templates]] feature enables you to quickly insert code blocks into your Org files in combination with =org-tempo= by typing =<= followed by the template name like =el= or =py= and then press =TAB=.  For example, to insert an empty =emacs-lisp= block below, you can type =<el= and press =TAB= to expand into such a block.

You can add more =src= block templates below by copying one of the lines and changing the two strings at the end, the first to be the template name and the second to contain the name of the language [[https://orgmode.org/worg/org-contrib/babel/languages.html][as it is known by Org Babel]].

#+begin_src emacs-lisp

  ;; This is needed as of Org 9.2
  (require 'org-tempo)

  (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
  (add-to-list 'org-structure-template-alist '("py" . "src python"))

#+end_src

** Org id
#+begin_src emacs-lisp
  (require 'org-id)
  ;; add uuid as ID in property for linking
  ;; stores id/links in ~/.emacs.d/.org-id-locations
  ;; use org-id-update-id-locations to update links if files moved/renamed
  (setq org-id-link-to-org-use-id t)
#+end_src
** Auto-tangle Configuration Files

This snippet adds a hook to =org-mode= buffers so that =efs/org-babel-tangle-config= gets executed each time such a buffer gets saved.  This function checks to see if the file being saved is the Emacs.org file you're looking at right now, and if so, automatically exports the configuration here to the associated output files.

#+begin_src emacs-lisp

  ;; Automatically tangle our Emacs.org config file when we save it
  (defun efs/org-babel-tangle-config ()
    (when (string-equal (file-name-directory (buffer-file-name))
                        (expand-file-name user-emacs-directory))
      ;; Dynamic scoping to the rescue
      (let ((org-confirm-babel-evaluate nil))
        (org-babel-tangle))))

  (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'efs/org-babel-tangle-config)))

#+end_src

* Org Web Tools
#+begin_src emacs_lisp
(use-package org-web-tools)
#+end_src
* Org Roam
** Configuration
#+begin_src emacs-lisp
(use-package org-roam
  :hook
  (after-init . org-roam-mode)
  :custom
  (org-roam-directory "/mnt/Data2/Documents/Roam/")
  (org-roam-completion-everywhere t)
  (org-roam-completion-system 'default)
  (org-roam-capture-templates
    '(("d" "default" plain
       #'org-roam-capture--get-point
       "%?"
       :file-name "%<%Y%m%d%H%M%S>-${slug}"
       :head "#+title: ${title}\n"
       :unnarrowed t)
      ("ll" "link note" plain
       #'org-roam-capture--get-point
       "* %^{Link}"
       :file-name "Inbox"
       :olp ("Links")
       :unnarrowed t
       :immediate-finish)
      ("lt" "link task" entry
       #'org-roam-capture--get-point
       "* TODO %^{Link}"
       :file-name "Inbox"
       :olp ("Tasks")
       :unnarrowed t
       :immediate-finish)))
  (org-roam-dailies-directory "Journal/")
  (org-roam-dailies-capture-templates
    '(("d" "default" entry
       #'org-roam-capture--get-point
       "* %?"
       :file-name "Journal/%<%Y-%m-%d>"
       :head "#+title: %<%Y-%m-%d %a>\n\n[[roam:%<%Y-%B>]]\n\n")
      ("t" "Task" entry
       #'org-roam-capture--get-point
       "* TODO %?\n  %U\n  %a\n  %i"
       :file-name "Journal/%<%Y-%m-%d>"
       :olp ("Tasks")
       :empty-lines 1
       :head "#+title: %<%Y-%m-%d %a>\n\n[[roam:%<%Y-%B>]]\n\n")
      ("j" "journal" entry
       #'org-roam-capture--get-point
       "* %<%I:%M %p> - Journal  :journal:\n\n%?\n\n"
       :file-name "Journal/%<%Y-%m-%d>"
       :olp ("Log")
       :head "#+title: %<%Y-%m-%d %a>\n\n[[roam:%<%Y-%B>]]\n\n")
      ("l" "log entry" entry
       #'org-roam-capture--get-point
       "* %<%I:%M %p> - %?"
       :file-name "Journal/%<%Y-%m-%d>"
       :olp ("Log")
       :head "#+title: %<%Y-%m-%d %a>\n\n[[roam:%<%Y-%B>]]\n\n")
      ("m" "meeting" entry
       #'org-roam-capture--get-point
       "* %<%I:%M %p> - %^{Meeting Title}  :meetings:\n\n%?\n\n"
       :file-name "Journal/%<%Y-%m-%d>"
       :olp ("Log")
       :head "#+title: %<%Y-%m-%d %a>\n\n[[roam:%<%Y-%B>]]\n\n")))
  :bind (:map org-roam-mode-map
          (("C-c n l"   . org-roam)
           ("C-c n f"   . org-roam-find-file)
           ("C-c n d"   . org-roam-dailies-find-date)
           ("C-c n c"   . org-roam-dailies-capture-today)
           ("C-c n C r" . org-roam-dailies-capture-tomorrow)
           ("C-c n t"   . org-roam-dailies-find-today)
           ("C-c n y"   . org-roam-dailies-find-yesterday)
           ("C-c n r"   . org-roam-dailies-find-tomorrow)
           ("C-c n g"   . org-roam-graph))
         :map org-mode-map
         (("C-c n i" . org-roam-insert))
         (("C-c n I" . org-roam-insert-immediate))))
#+end_src
* Deft
#+begin_src emacs-lisp
(use-package deft
  :commands (deft)
  :config (setq deft-directory "/mnt/Data2/Documents/Roam"
                deft-recursive t
                deft-extensions '("md" "org")))
#+end_src
* Development
** Compile
Use use-package to set some defaults for the built in 'compile' feature.
#+begin_src emacs-lisp
  ;;; compilation
  (use-package compile
    :bind (("C-x M-m" . compile)
           ("C-x C-m" . recompile))
    :config
    (setq compilation-scroll-output t)
    (require 'ansi-color)
    (defun colorize-compilation-buffer ()
      (let ((inhibit-read-only t))
        (ansi-color-apply-on-region (point-min) (point-max))))
    (add-hook 'compilation-filter-hook 'colorize-compilation-buffer)
    )
#+end_src
If you have a special environment, you can set environment variables for that environment:
#+begin_src emacs-lisp :tangle no
(setq compilation-environment '("HOME=/root"))
#+end_src
** Languages
*** Flycheck
Flycheck will help with understanding linting issues
#+begin_src emacs-lisp
  (use-package flycheck
    :ensure t)
#+end_src
*** IDE Features with lsp-mode

**** lsp-mode

We use the excellent [[https://emacs-lsp.github.io/lsp-mode/][lsp-mode]] to enable IDE-like functionality for many different programming languages via "language servers" that speak the [[https://microsoft.github.io/language-server-protocol/][Language Server Protocol]].  Before trying to set up =lsp-mode= for a particular language, check out the [[https://emacs-lsp.github.io/lsp-mode/page/languages/][documentation for your language]] so that you can learn which language servers are available and how to install them.

The =lsp-keymap-prefix= setting enables you to define a prefix for where =lsp-mode='s default keybindings will be added.  I *highly recommend* using the prefix to find out what you can do with =lsp-mode= in a buffer.

The =which-key= integration adds helpful descriptions of the various keys so you should be able to learn a lot just by pressing =C-c l= in a =lsp-mode= buffer and trying different things that you find there.

#+begin_src emacs-lisp

  (defun efs/lsp-mode-setup ()
    (setq lsp-headerline-breadcrumb-segments '(path-up-to-project file symbols))
    (lsp-headerline-breadcrumb-mode))

  (use-package lsp-mode
    :commands (lsp lsp-deferred)
    :hook (lsp-mode . efs/lsp-mode-setup)
    :init
    (setq lsp-keymap-prefix "C-c l")  ;; Or 'C-l', 's-l'
    :config
    (lsp-enable-which-key-integration t))

#+end_src

**** lsp-ui

[[https://emacs-lsp.github.io/lsp-ui/][lsp-ui]] is a set of UI enhancements built on top of =lsp-mode= which make Emacs feel even more like an IDE.  Check out the screenshots on the =lsp-ui= homepage (linked at the beginning of this paragraph) to see examples of what it can do.

#+begin_src emacs-lisp

  (use-package lsp-ui
    :hook (lsp-mode . lsp-ui-mode)
    :custom
    (lsp-ui-doc-position 'bottom))

#+end_src

**** lsp-treemacs

[[https://github.com/emacs-lsp/lsp-treemacs][lsp-treemacs]] provides nice tree views for different aspects of your code like symbols in a file, references of a symbol, or diagnostic messages (errors and warnings) that are found in your code.

Try these commands with =M-x=:

- =lsp-treemacs-symbols= - Show a tree view of the symbols in the current file
- =lsp-treemacs-references= - Show a tree view for the references of the symbol under the cursor
- =lsp-treemacs-error-list= - Show a tree view for the diagnostic messages in the project

This package is built on the [[https://github.com/Alexander-Miller/treemacs][treemacs]] package which might be of some interest to you if you like to have a file browser at the left side of your screen in your editor.

#+begin_src emacs-lisp

  (use-package lsp-treemacs
    :after lsp)

#+end_src

**** lsp-ivy

[[https://github.com/emacs-lsp/lsp-ivy][lsp-ivy]] integrates Ivy with =lsp-mode= to make it easy to search for things by name in your code.  When you run these commands, a prompt will appear in the minibuffer allowing you to type part of the name of a symbol in your code.  Results will be populated in the minibuffer so that you can find what you're looking for and jump to that location in the code upon selecting the result.

Try these commands with =M-x=:

- =lsp-ivy-workspace-symbol= - Search for a symbol name in the current project workspace
- =lsp-ivy-global-workspace-symbol= - Search for a symbol name in all active project workspaces

#+begin_src emacs-lisp

  (use-package lsp-ivy)

#+end_src

*** Debugging with dap-mode

[[https://emacs-lsp.github.io/dap-mode/][dap-mode]] is an excellent package for bringing rich debugging capabilities to Emacs via the [[https://microsoft.github.io/debug-adapter-protocol/][Debug Adapter Protocol]].  You should check out the [[https://emacs-lsp.github.io/dap-mode/page/configuration/][configuration docs]] to learn how to configure the debugger for your language.  Also make sure to check out the documentation for the debug adapter to see what configuration parameters are available to use for your debug templates!

#+begin_src emacs-lisp

  (use-package dap-mode
    ;; Uncomment the config below if you want all UI panes to be hidden by default!
    ;; :custom
    ;; (lsp-enable-dap-auto-configure nil)
    ;; :config
    ;; (dap-ui-mode 1)

    :config
    ;; Set up Node debugging
    (require 'dap-node)
    (dap-node-setup) ;; Automatically installs Node debug adapter if needed

    ;; Bind `C-c l d` to `dap-hydra` for easy access
    (general-define-key
      :keymaps 'lsp-mode-map
      :prefix lsp-keymap-prefix
      "d" '(dap-hydra t :wk "debugger")))

#+end_src

*** C++
 We will use ccls as the lsp server.
 Make sure that ccls is installed on the system.
 #+begin_src emacs-lisp
  (use-package ccls
    :ensure t
    :config
    (setq ccls-executable "ccls")
    (setq lsp-prefer-flymake nil)
    (setq-default flycheck-disabled-checkers '(c/c++-clang c/c++-cppcheck c/c++-gcc))
    :hook ((c-mode c++-mode objc-mode) .
           (lambda () (require 'ccls) (lsp))))
 #+end_src

#+begin_src emacs-lisp
  (defun my-c-mode-common-hook ()
   ;; my customizations for all of c-mode, c++-mode, objc-mode, java-mode
   (c-set-offset 'substatement-open 0)
   ;; other customizations can go here

   (setq c++-tab-always-indent t)
   (setq c-basic-offset 4)                  ;; Default is 2
   (setq c-indent-level 4)                  ;; Default is 2
   ;; (setq compile-command "cd ${PWD/%src*/build} && cmake ../src && make")
   (setq compile-command "cd ${PWD/%src} && cmake --build build")

   (setq tab-stop-list '(4 8 12 16 20 24 28 32 36 40 44 48 52 56 60))
   (setq tab-width 4)
   (setq indent-tabs-mode nil)  ; use spaces only if nil, t for tabs
   )

  (add-hook 'c-mode-common-hook 'my-c-mode-common-hook)
#+end_src
*** TypeScript

This is a basic configuration for the TypeScript language so that =.ts= files activate =typescript-mode= when opened.  We're also adding a hook to =typescript-mode-hook= to call =lsp-deferred= so that we activate =lsp-mode= to get LSP features every time we edit TypeScript code.

#+begin_src emacs-lisp

  (use-package typescript-mode
    :mode "\\.ts\\'"
    :hook (typescript-mode . lsp-deferred)
    :config
    (setq typescript-indent-level 2))

#+end_src

*Important note!*  For =lsp-mode= to work with TypeScript (and JavaScript) you will need to install a language server on your machine.  If you have Node.js installed, the easiest way to do that is by running the following command:

#+begin_src shell :tangle no

npm install -g typescript-language-server typescript

#+end_src

This will install the [[https://github.com/theia-ide/typescript-language-server][typescript-language-server]] and the TypeScript compiler package.

*** Python

We use =lsp-mode= and =dap-mode= to provide a more complete development environment for Python in Emacs.  Check out [[https://emacs-lsp.github.io/lsp-mode/page/lsp-pyls/][the =pyls= configuration]] in the =lsp-mode= documentation for more details.

Make sure you have the =pyls= language server installed before trying =lsp-mode=!

#+begin_src sh :tangle no

pip install --user "python-language-server[all]"
pip install debugpy

#+end_src

There are a number of other language servers for Python so if you find that =pyls= doesn't work for you, consult the =lsp-mode= [[https://emacs-lsp.github.io/lsp-mode/page/languages/][language configuration documentation]] to try the others!

#+begin_src emacs-lisp

  (use-package python-mode
    :ensure t
    :hook (python-mode . lsp-deferred)
    :custom
    ;; NOTE: Set these if Python 3 is called "python3" on your system!
    ;; (python-shell-interpreter "python3")
    ;; (dap-python-executable "python3")
    (dap-python-debugger 'debugpy)
    :config
    (require 'dap-python))

  (defun run-with-python ()
    "Set the default compile-command to run the current file with python"
    (setq-local compile-command
                (concat "python"
                        (when buffer-file-name
                          (shell-quote-argument buffer-file-name)))))
  (add-hook 'python-mode-hook 'run-with-python)

#+end_src

You can use the pyvenv package to use =virtualenv= environments in Emacs.  The =pyvenv-activate= command should configure Emacs to cause =lsp-mode= and =dap-mode= to use the virtual environment when they are loaded, just select the path to your virtual environment before loading your project.

#+begin_src emacs-lisp

  (use-package pyvenv
    :config
    (pyvenv-mode 1))

#+end_src

*** Lisp
#+begin_src emacs-lisp

  (use-package sly
    :config
    (setq inferior-lisp-program "/usr/bin/sbcl"))

#+end_src
*** Golang
The configuration requires that the gopls language server is installed on the system.
#+begin_src sh :tangle no
  go install golang.org/x/tools/gopls@latest
  go install golang.org/x/tools/cmd/goimports@latest
  go install golang.org/x/tools/cmd/godoc@latest
#+end_src

#+begin_src emacs-lisp
    (use-package go-mode
    :ensure t
    :hook ((go-mode . lsp-deferred)
           (go-mode . company-mode))
    :bind (:map go-mode-map
                ("C-c 6" . gofmt))
    :config
    (require 'lsp-go)
    ;; https:/github.com/golang/tools/blob/master/gopls/doc/analyzers.md
    (setq lsp-go-analyses
          '((fieldalignment . t)
            (nilness        . t)
            (shadow         . t)
            (unusedwrite    . t)
            (unusedparams   . t)
            (unusedVariable . t)))
    ;; GOPATH/bin
    (add-to-list 'exec-path "~/go/bin")
    (setq gofmt-command "goimports"))
#+end_src
** Company Mode

[[http://company-mode.github.io/][Company Mode]] provides a nicer in-buffer completion interface than =completion-at-point= which is more reminiscent of what you would expect from an IDE.  We add a simple configuration to make the keybindings a little more useful (=TAB= now completes the selection and initiates completion at the current location if needed).

We also use [[https://github.com/sebastiencs/company-box][company-box]] to further enhance the look of the completions with icons and better overall presentation.

#+begin_src emacs-lisp

(use-package company
  :after lsp-mode
  :hook (lsp-mode . company-mode)
  :bind (:map company-active-map
         ("C-j" . company-select-next)
         ("C-k" . company-select-previous)
         ("<tab>" . company-complete-selection))
        (:map lsp-mode-map
         ("<tab>" . company-indent-or-complete-common))
  :custom
  (company-minimum-prefix-length 1)
  (company-tooltip-limit 14)
  (company-tooltip-align-annotations t)
  (company-require-match 'never)
  (company-global-modes '(not erc-mode message-mode help-mode gud-mode))
  (company-frontends
   '(company-pseudo-tooltip-frontend  ; always show candidates in overlay tooltip
    company-echo-metadata-frontend))  ; show selected candidate docs in echo area
  (company-backends '(company-capf company-files company-keywords))
  (company-auto-complete nil)
  (company-auto-complete-chars nil)
  (company-dabbrev-other-buffers nil)
  (company-dabbrev-ignore-case nil)
  (company-dabbrev-downcase nil)
  (company-idle-delay 0.0))

(use-package company-box
  :hook (company-mode . company-box-mode))

#+end_src

** Projectile

[[https://projectile.mx/][Projectile]] is a project management library for Emacs which makes it a lot easier to navigate around code projects for various languages.  Many packages integrate with Projectile so it's a good idea to have it installed even if you don't use its commands directly.

#+begin_src emacs-lisp

  (use-package projectile
    :diminish projectile-mode
    :config (projectile-mode)
    :custom ((projectile-completion-system 'ivy))
    :bind-keymap
    ("C-c p" . projectile-command-map)
    :init
    ;; NOTE: Set this to the folder where you keep your Git repos!
    (when (file-directory-p "~/dev")
      (setq projectile-project-search-path '("~/dev")))
    (setq projectile-switch-project-action #'projectile-dired))

  (use-package counsel-projectile
    :config (counsel-projectile-mode))

#+end_src

** Magit

[[https://magit.vc/][Magit]] is the best Git interface I've ever used.  Common Git operations are easy to execute quickly using Magit's command panel system.

#+begin_src emacs-lisp

  (use-package magit
    :custom
    (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))

  ;; NOTE: Make sure to configure a GitHub token before using this package!
  ;; - https://magit.vc/manual/forge/Token-Creation.html#Token-Creation
  ;; - https://magit.vc/manual/ghub/Getting-Started.html#Getting-Started
  (use-package forge)

#+end_src

** Commenting

Emacs' built in commenting functionality =comment-dwim= (usually bound to =M-;=) doesn't always comment things in the way you might expect so we use [[https://github.com/redguardtoo/evil-nerd-commenter][evil-nerd-commenter]] to provide a more familiar behavior.  I've bound it to =M-/= since other editors sometimes use this binding but you could also replace Emacs' =M-;= binding with this command.

#+begin_src emacs-lisp

  (use-package evil-nerd-commenter
    :bind ("M-/" . evilnc-comment-or-uncomment-lines))

#+end_src

** Rainbow Delimiters

[[https://github.com/Fanael/rainbow-delimiters][rainbow-delimiters]] is useful in programming modes because it colorizes nested parentheses and brackets according to their nesting depth.  This makes it a lot easier to visually match parentheses in Emacs Lisp code without having to count them yourself.

#+begin_src emacs-lisp

(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode))

#+end_src

** YASnippet
*** Installation
#+begin_src emacs-lisp
  (use-package yasnippet
    :config
    (setq yas-snippet-dirs '("~/.emacs.d/snippets"))
    (yas-global-mode 1))
#+end_src
*** Create a snippet
Run *yas-new-snippet* to create a new snippet.
#+begin_example :notangle
# --
# name: <name>
# key: <d
# --

#+BEGIN_SRC
$0
#+END_SRC
#+end_example

*key:* defines the key combbination to type + TAB to expand into the text defined
*$0* defines the location of the cursor once the text is inserted
*** Save a snippet
When creating a snippet, save it in the directory specified above in config, in a folder for the mode.
So if creating a snippet for org-mode, save in folder ~/.dotfiles/snippets/org-mode
Do not give the saved file an extension.
*** Forms
You can make a more complex snippet with forms, which will prompt user to fill in fields of the expanded text.
#+begin_example
# --
# name: titler
# key: <tt
# --

#+TITLE: ${1:title}
#+AUTHOR: ${2:author}

$0
#+end_example
The *${#:name}* format allows user input into setting form fields.  After entering text, TAB will move to the next field or cursor position ($0).

Automatically detect and set the virtual environment.
#+begin_src emacs-lisp
;; Automatically set the virtual environment when entering a directory
(use-package auto-virtualenv
  :defer 2
  :config
  (add-hook 'python-mode-hook 'auto-virtualenv-set-virtualenv))
#+end_src

* Terminals

** term-mode

=term-mode= is a built-in terminal emulator in Emacs.  Because it is written in Emacs Lisp, you can start using it immediately with very little configuration.  If you are on Linux or macOS, =term-mode= is a great choice to get started because it supports fairly complex terminal applications (=htop=, =vim=, etc) and works pretty reliably.  However, because it is written in Emacs Lisp, it can be slower than other options like =vterm=.  The speed will only be an issue if you regularly run console apps with a lot of output.

One important thing to understand is =line-mode= versus =char-mode=.  =line-mode= enables you to use normal Emacs keybindings while moving around in the terminal buffer while =char-mode= sends most of your keypresses to the underlying terminal.  While using =term-mode=, you will want to be in =char-mode= for any terminal applications that have their own keybindings.  If you're just in your usual shell, =line-mode= is sufficient and feels more integrated with Emacs.

With =evil-collection= installed, you will automatically switch to =char-mode= when you enter Evil's insert mode (press =i=).  You will automatically be switched back to =line-mode= when you enter Evil's normal mode (press =ESC=).

Run a terminal with =M-x term!=

*Useful key bindings:*

- =C-c C-p= / =C-c C-n= - go back and forward in the buffer's prompts (also =[[= and =]]= with evil-mode)
- =C-c C-k= - Enter char-mode
- =C-c C-j= - Return to line-mode
- If you have =evil-collection= installed, =term-mode= will enter char mode when you use Evil's Insert mode

#+begin_src emacs-lisp

  (use-package term
    :config
    (setq explicit-shell-file-name "bash") ;; Change this to zsh, etc
    ;;(setq explicit-zsh-args '())         ;; Use 'explicit-<shell>-args for shell-specific args

    ;; Match the default Bash shell prompt.  Update this if you have a custom prompt
    (setq term-prompt-regexp "^[^#$%>\n]*[#$%>] *"))

#+end_src

*** Better term-mode colors

The =eterm-256color= package enhances the output of =term-mode= to enable handling of a wider range of color codes so that many popular terminal applications look as you would expect them to.  Keep in mind that this package requires =ncurses= to be installed on your machine so that it has access to the =tic= program.  Most Linux distributions come with this program installed already so you may not have to do anything extra to use it.

#+begin_src emacs-lisp

  (use-package eterm-256color
    :hook (term-mode . eterm-256color-mode))

#+end_src

** vterm

[[https://github.com/akermu/emacs-libvterm/][vterm]] is an improved terminal emulator package which uses a compiled native module to interact with the underlying terminal applications.  This enables it to be much faster than =term-mode= and to also provide a more complete terminal emulation experience.

Make sure that you have the [[https://github.com/akermu/emacs-libvterm/#requirements][necessary dependencies]] installed before trying to use =vterm= because there is a module that will need to be compiled before you can use it successfully.

#+begin_src emacs-lisp

  (use-package vterm
    :commands vterm
    :config
    (setq term-prompt-regexp "^[^#$%>\n]*[#$%>] *")  ;; Set this to match your custom shell prompt
    ;;(setq vterm-shell "zsh")                       ;; Set this to customize the shell to launch
    (setq vterm-max-scrollback 10000))

#+end_src

** shell-mode

[[https://www.gnu.org/software/emacs/manual/html_node/emacs/Interactive-Shell.html#Interactive-Shell][shell-mode]] is a middle ground between =term-mode= and Eshell.  It is *not* a terminal emulator so more complex terminal programs will not run inside of it.  It does have much better integration with Emacs because all command input in this mode is handled by Emacs and then sent to the underlying shell once you press Enter.  This means that you can use =evil-mode='s editing motions on the command line, unlike in the terminal emulator modes above.

*Useful key bindings:*

- =C-c C-p= / =C-c C-n= - go back and forward in the buffer's prompts (also =[[= and =]]= with evil-mode)
- =M-p= / =M-n= - go back and forward in the input history
- =C-c C-u= - delete the current input string backwards up to the cursor
- =counsel-shell-history= - A searchable history of commands typed into the shell

One advantage of =shell-mode= on Windows is that it's the only way to run =cmd.exe=, PowerShell, Git Bash, etc from within Emacs.  Here's an example of how you would set up =shell-mode= to run PowerShell on Windows:

#+begin_src emacs-lisp

  (when (eq system-type 'windows-nt)
    (setq explicit-shell-file-name "powershell.exe")
    (setq explicit-powershell.exe-args '()))

#+end_src

** Eshell

[[https://www.gnu.org/software/emacs/manual/html_mono/eshell.html#Contributors-to-Eshell][Eshell]] is Emacs' own shell implementation written in Emacs Lisp.  It provides you with a cross-platform implementation (even on Windows!) of the common GNU utilities you would find on Linux and macOS (=ls=, =rm=, =mv=, =grep=, etc).  It also allows you to call Emacs Lisp functions directly from the shell and you can even set up aliases (like aliasing =vim= to =find-file=).  Eshell is also an Emacs Lisp REPL which allows you to evaluate full expressions at the shell.

The downsides to Eshell are that it can be harder to configure than other packages due to the particularity of where you need to set some options for them to go into effect, the lack of shell completions (by default) for some useful things like Git commands, and that REPL programs sometimes don't work as well.  However, many of these limitations can be dealt with by good configuration and installing external packages, so don't let that discourage you from trying it!

*Useful key bindings:*

- =C-c C-p= / =C-c C-n= - go back and forward in the buffer's prompts (also =[[= and =]]= with evil-mode)
- =M-p= / =M-n= - go back and forward in the input history
- =C-c C-u= - delete the current input string backwards up to the cursor
- =counsel-esh-history= - A searchable history of commands typed into Eshell

We will be covering Eshell more in future videos highlighting other things you can do with it.

For more thoughts on Eshell, check out these articles by Pierre Neidhardt:
- https://ambrevar.xyz/emacs-eshell/index.html
- https://ambrevar.xyz/emacs-eshell-versus-shell/index.html

#+begin_src emacs-lisp

  (defun efs/configure-eshell ()
    ;; Save command history when commands are entered
    (add-hook 'eshell-pre-command-hook 'eshell-save-some-history)

    ;; Truncate buffer for performance
    (add-to-list 'eshell-output-filter-functions 'eshell-truncate-buffer)

    ;; Bind some useful keys for evil-mode
    (evil-define-key '(normal insert visual) eshell-mode-map (kbd "C-r") 'counsel-esh-history)
    (evil-define-key '(normal insert visual) eshell-mode-map (kbd "<home>") 'eshell-bol)
    (evil-normalize-keymaps)

    (setq eshell-history-size         10000
          eshell-buffer-maximum-lines 10000
          eshell-hist-ignoredups t
          eshell-scroll-to-bottom-on-input t))

  (use-package eshell-git-prompt)

  (use-package eshell
    :hook (eshell-first-time-mode . efs/configure-eshell)
    :config

    (with-eval-after-load 'esh-opt
      (setq eshell-destroy-buffer-when-process-dies t))
      ;; defaults for eshell-visual-commands contains more/better options
      ;; (setq eshell-visual-commands '("htop" "zsh" "vim")))

    (eshell-git-prompt-use-theme 'powerline))


#+end_src

* File Management

** Dired

Dired is a built-in file manager for Emacs that does some pretty amazing things!  Here are some key bindings you should try out:

*** Key Bindings

**** Navigation

*Emacs* / *Evil*
- =n= / =j= - next line
- =p= / =k= - previous line
- =j= / =J= - jump to file in buffer
- =RET= - select file or directory
- =^= - go to parent directory
- =S-RET= / =g O= - Open file in "other" window
- =M-RET= - Show file in other window without focusing (previewing files)
- =g o= (=dired-view-file=) - Open file but in a "preview" mode, close with =q=
- =g= / =g r= Refresh the buffer with =revert-buffer= after changing configuration (and after filesystem changes!)

**** Marking files

- =m= - Marks a file
- =u= - Unmarks a file
- =U= - Unmarks all files in buffer
- =* t= / =t= - Inverts marked files in buffer
- =% m= - Mark files in buffer using regular expression
- =*= - Lots of other auto-marking functions
- =k= / =K= - "Kill" marked items (refresh buffer with =g= / =g r= to get them back)
- Many operations can be done on a single file if there are no active marks!

**** Copying and Renaming files

- =C= - Copy marked files (or if no files are marked, the current file)
- Copying single and multiple files
- =U= - Unmark all files in buffer
- =R= - Rename marked files, renaming multiple is a move!
- =% R= - Rename based on regular expression: =^test= , =old-\&=

*Power command*: =C-x C-q= (=dired-toggle-read-only=) - Makes all file names in the buffer editable directly to rename them!  Press =Z Z= to confirm renaming or =Z Q= to abort.

**** Deleting files

- =D= - Delete marked file
- =d= - Mark file for deletion
- =x= - Execute deletion for marks
- =delete-by-moving-to-trash= - Move to trash instead of deleting permanently

**** Creating and extracting archives

- =Z= - Compress or uncompress a file or folder to (=.tar.gz=)
- =c= - Compress selection to a specific file
- =dired-compress-files-alist= - Bind compression commands to file extension

**** Other common operations

- =T= - Touch (change timestamp)
- =M= - Change file mode
- =O= - Change file owner
- =G= - Change file group
- =S= - Create a symbolic link to this file
- =L= - Load an Emacs Lisp file into Emacs

*** Configuration

#+begin_src emacs-lisp

  (use-package dired
    :ensure nil
    :commands (dired dired-jump)
    :bind (("C-x C-j" . dired-jump))
    :custom ((dired-listing-switches "-agho --group-directories-first"))
    :config
    (evil-collection-define-key 'normal 'dired-mode-map
      "h" 'dired-single-up-directory
      "l" 'dired-single-buffer))

  ;; (use-package dired-single)

  (use-package all-the-icons-dired
    :hook (dired-mode . all-the-icons-dired-mode))

  (use-package dired-open
    :config
    ;; Doesn't work as expected!
    ;;(add-to-list 'dired-open-functions #'dired-open-xdg t)
    (setq dired-open-extensions '(("png" . "feh")
                                  ("mkv" . "mpv"))))

  (use-package dired-hide-dotfiles
    :hook (dired-mode . dired-hide-dotfiles-mode)
    :config
    (evil-collection-define-key 'normal 'dired-mode-map
      "H" 'dired-hide-dotfiles-mode))

  ;; Enable using 'a' key to prevent creation of new buffer when
  ;; navigating directories
  (put 'dired-find-alternate-file 'disabled nil)
#+end_src

* Spellcheck
Enable Flyspell for spell checking.  Certain modes/regions will be ignored.  Requires `aspell` to be installed.
#+begin_src emacs-lisp
(use-package flyspell
  :defer t
  :config
  (add-to-list 'ispell-skip-region-alist '("~" "~"))
  (add-to-list 'ispell-skip-region-alist '("=" "="))
  (add-to-list 'ispell-skip-region-alist '("^#\\+BEGIN_SRC" . "^#\\+END_SRC"))
  (add-to-list 'ispell-skip-region-alist '("^#\\+BEGIN_EXPORT" . "^#\\+END_EXPORT"))
  (add-to-list 'ispell-skip-region-alist '("^#\\+BEGIN_EXPORT" . "^#\\+END_EXPORT"))
  (add-to-list 'ispell-skip-region-alist '(":\\(PROPERTIES\\|LOGBOOK\\):" . ":END:"))

  (dolist (mode '(org-mode-hook
                  mu4e-compose-mode-hook))
    (add-hook mode (lambda () (flyspell-mode 1))))
  :general ;; Switches correct word from middle click to right click
  (general-define-key :keymaps 'flyspell-mouse-map
                      "<mouse-3>" #'flyspell-correct-word
                      "<mouse-2>" nil)
  )
#+end_src
* Super-save
 Automatically save files when idel or switching buffers.
 #+begin_src emacs-lisp
(use-package super-save
  :diminish super-save-mode
  :defer 2
  :config
  (setq super-save-auto-save-when-idle t)
  (setq super-save-idle-duration 5) ;; after 5 seconds of not typing autosave
  (setq super-save-triggers ;; Functions after which buffers are saved (switching window, for example)
        '(evil-window-next evil-window-prev balance-windows other-window))
  (super-save-mode +1))
 #+end_src

* Saveplace
Automatically save the last position in a file so can return to last spot when reopening the file.
#+begin_src emacs-lisp
(use-package saveplace
  :init (setq save-place-limit 100)
  :config (save-place-mode))
#+end_src

* Pdf-tools
#+begin_src emacs-lisp
;;(use-package pdf-tools
;;  :defer t
;;  :pin manual
;;  :mode  ("\\.pdf\\'" . pdf-view-mode)
;;  :config
;;  (pdf-loader-install)
;;  (setq-default pdf-view-display-size 'fit-height)
;;  (setq pdf-view-continuous nil) ;; Makes it so scrolling down to the bottom/top of a page doesn't switch to the next page
;;  (setq pdf-view-midnight-colors '("#ffffff" . "#121212" )) ;; I use midnight mode as dark mode, dark mode doesn't seem to work
;;  :general
;;  (general-define-key :states 'motion :keymaps 'pdf-view-mode-map
;;                      "j" 'pdf-view-next-page
;;                      "k" 'pdf-view-previous-page
;;                      "C-j" 'pdf-view-next-line-or-next-page
;;                      "C-k" 'pdf-view-next-line-or-next-page
;;
;;                      ;; Arrows for movement as well
;;                      (kbd "<down>") 'pdf-view-next-line-or-next-page
;;                      (kbd "<up>") 'pdf-view-previous-line-or-next-page
;;                      (kbd "<left>") 'image-backward-hscroll
;;                      (kbd "<right>") 'image-forward-hscroll
;;
;;                      "H" 'pdf-view-fit-height-to-window
;;                      "0" 'pdf-view-fit-height-to-window
;;                      "W" 'pdf-view-fit-width-to-window
;;                      "=" 'pdf-view-enlarge
;;                      "-" 'pdf-view-shrink
;;
;;                      "q" 'quit-window
;;                      "Q" 'kill-this-buffer
;;                      "g" 'revert-buffer
;;                      )
;;  )
#+end_src
* Elfeed
#+begin_src emacs-lisp
  (use-package elfeed :ensure t
  :config (elfeed-set-max-connections 32))
  (use-package elfeed-org :ensure t
    :config
    (progn
      (elfeed-org)
      (setq rmh-elfeed-org-files (list "/mnt/Data2/Documents/kb/emacs/elfeed.org"))))

  (define-key global-map (kbd "C-c e") #'elfeed)
#+end_src
* Applications

** Some App

This is an example of configuring another non-Emacs application using org-mode.  Not only do we write out the configuration at =.config/some-app/config=, we also compute the value that gets stored in this configuration from the Emacs Lisp block above it.

#+NAME: the-value
#+begin_src emacs-lisp :tangle no

  (+ 55 100)

#+end_src

*NOTE*: Set the =:tangle= parameter below to =.config/some-app/config= for this to work!

#+begin_src conf :tangle no :noweb yes

  value=<<the-value()>>

#+end_src
** dashboard
#+begin_src emacs-lisp
  (if (not msystem)
      (use-package dashboard
	:ensure t
	:init
	(progn
	  (setq dashboard-items '((recents .7)
				  (projects . 3)))
	  (setq dashboard-show-shortcuts t)
	  (setq dashboard-center-content nil)
	  (setq dashboard-banner-logo-title "Find a place to start...")
	  (setq dashboard-set-file-icons t)
	  (setq dashboard-set-heading-icons t)
	  ;;(setq dashboard-startup-banner "")
	  )
	:config
	(dashboard-setup-startup-hook)))
#+end_src

* Publish
Org-publish
#+begin_src emacs-lisp
  (setq org-publish-use-timestamps-flag nil)
  (setq org-export-with-broken-links t)
  (setq org-publish-project-alist
      '(("imagineallthings.com"
         :base-directory "/mnt/Data2/dev/GitHub/imagineallthings.com/"
         :base-extension "org"
         :publishing-directory "/mnt/Data2/dev/GitHub/imagineallthings.com/html/"
         :recursive t
         :exclude "org-html-themes/.*"
         :publishing-function org-html-publish-to-html
         :headline-levels 4
         :auto-preamble t)
        ("images"
         :base-directory "/mnt/Data2/dev/GitHub/imagineallthings.com/blog/img/"
         :base-extension "png\\|jpg\\|jpeg"
         :publishing-directory "/mnt/Data2/dev/GitHub/imagineallthings.com/html/blog/img/"
         :publishing-function org-publish-attachment)
        ("website" :components("imagineallthings.com" "images"))))
#+end_src

* Presentation
** Install
The ox-reveal package will  allow you to make presentations from org files
#+begin_src emacs-lisp :notangle
;; (use-package ox-reveal)
#+end_src
** Setup in org file
In the org file to use as a presentation, the following must be added at the top of the file
#+begin_example :notangle
:REVEAL_PROPERTIES:
#+REVEAL_ROOT: https://cnd.jsdelivr.net/npm/reveal.js
#+REVEAL_REVEAL_JS_VERSION: 4
#+REVEAL_THEME: serif
#+OPTIONS: timestamp:nil  toc:1 num:nil
:END:
#+end_example
Next run *org-export-dispatch*, then menu options R,b to open presentation in browser.
To prevent a list of items from appearing immediately in the presentation place the following above the list items:
#+begin_example :notangle
#+ATTR_REVEAL: :frag (appear)
#+end_example
When pressing the 'space' bar the items will appear one at a time.
** Images
Use the ATTR_HTML option below placed above the image url.
#+begin_example :notangle
#+ATTR_HTML: :width 45% :align center
<image URL
#+end_example
** Speaker Notes
Use the tags '#+BEGIN_NOTES' / '#+END_NOTES' to encapsulate notes for the speaker..  These should be placed just after the main heading for the note.
After starting the presentation, press the 's' key to open the presenting window and reveal speakers notes.
** Resources
[[https://www.youtube.com/watch?v=avtiR0AUVlo][YT Video For Emacs Org Mode  + org-reveal]]
[[https://github.com/yjwen/org-reveal][Org-reveal]]
[[https://revealjs.com/][Revealjs]]

* Latex
#+begin_src emacs-lisp
  ;; best latex preview functionality
    (if (not msystem)
	(use-package xenops
	  :config
	  (setq xenops-reveal-on-entry t)
	  ;;(add-hook 'LaTeX-mode-hook #'xenops-mode)
	  (add-hook 'org-mode-hook #'xenops-mode)
	  (add-hook 'xenops-mode-hook 'xenops-render)
	  (add-hook 'org-babel-after-execute-hook (lambda ()
						    (interactive)
						    (ignore-errors (xenops-render))))
	  (setq xenops-math-image-scale-factor 1.5)
	  (setcar (cdr (car xenops-elements))
		  '(:delimiters
		    ("^[ 	]*\\\\begin{\\(align\\|equation\\|gather\\)\\*?}" "^[ 	]*\\\\end{\\(align\\|equation\\|gather\\)\\*?}")
		    ("^[ 	]*\\\\\\[" "^[ 	]*\\\\\\]")))))
#+end_src

* EDIFF
#+begin_src emacs-lisp
  (setq ediff-split-window_function 'split-window-horizontally
        ediff-window-setup-function 'ediff-setup-windows-plain)
  (defun jem-ediff-hook()
    (ediff-setup-keymap)
    (define-key ediff-mode-map "j" 'ediff-next-difference)
    (define-key ediff-mode-map "k" 'ediff-previous-difference))

  (add-hook 'ediff-mode-hook 'jem-ediff-hook)

#+end_src
* plantuml
Plantuml requires java and graphviz to be installed.
#+begin_src emacs-lisp :notangle
(setq org-plantuml-jar-path (expand-file-name "/home/jeff/plantuml-mit-1.2025.3.jar"))
(add-to-list 'org-src-lang-modes '("plantuml" . plantuml))
(org-babel-do-load-languages 'org-babel-load-languages '((plantuml . t)))
#+end_src

* AI
#+begin_src emacs-lisp
(use-package gptel
    :config
    (setq
     gptel-model 'deepseek-r1:8b
     gptel-backend (gptel-make-ollama "Ollama"
                 :host "localhost:11434"
                 :stream t
                 ;;:models '(deepseek-r1:8b))))
                 :models '(rnj-1))))
#+end_src

* Custom files post config
These are custom emacs-lisp files to load after other packages are loaded and available.
#+begin_src emacs-lisp
;; bark -> book mark
;; save URLs to a file
;; not the same as emacs built in bookmark feature
;; (load (expand-file-name "bark.el" jem/custom-emacs))
(load "~/.emacs.d/custom-emacs/bark.el")
#+end_src
