
# Enable clipboard access
set-option -g default-command "reattach-to-user-namespace -l zsh"
setw -g mode-keys vi

# Bind 'v' to start selection and 'y' to copy to system clipboard
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

# Bind ']' to paste from system clipboard
bind ] run "reattach-to-user-namespace pbpaste | tmux load-buffer - && tmux paste-buffer"
